version: '3'

services:
  php-apache:
    build: .
    container_name: php-apache
    volumes:
      - ../app:/var/www/html
      - ../sites-config:/etc/apache2/sites-available/
    ports:
      - 8080:80
    working_dir: /var/www/html
    environment:
      PHP_ERROR_REPORTING: E_ALL & ~E_NOTICE
      PHP_DISPLAY_ERRORS: "Off"
      PHP_DISPLAY_STARTUP_ERRORS: "Off"
      PHP_LOG_ERRORS: "On"
      PHP_MAX_EXECUTION_TIME: 60
      PHP_MEMORY_LIMIT: 128M
      PHP_POST_MAX_SIZE: 50M
      PHP_UPLOAD_MAX_FILESIZE: 50M
    depends_on:
          - db

  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - ../app/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: projeto-db
      MYSQL_USER: aluno
      MYSQL_PASSWORD: my-password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - 8081:80
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: my-secret-pw
      UPLOAD_LIMIT: 50M
      PMA_USER: aluno
      PMA_PASSWORD: my-password
    depends_on:
      - db



 